services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    # networks:
    #   - inception

# networks:
#   inception:

# volumes:
#   v_mariadb:
#   v_wordpress:
