services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    env_file:
      - .env
    # image: nginx_img
    # ports:
      # - "8080:80"
    networks:
      inception:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    # image: mariadb_img
    # ports:
      # - "8080:80"
    networks:
      inception:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    # image: wordpress_img
    # ports:
      # - "8080:80"
    networks:
      inception:

networks:
  inception:

volumes:
