FROM debian:bullseye
	# Start with the debian:11.10 base image.
WORKDIR /mariadb
RUN 
	# Install MariaDB Server:
	# Update the package lists.
	# Install MariaDB server and any necessary dependencies.
	# Configure MariaDB:
	# Create and configure MariaDB databases and users.
	# Set appropriate permissions and security settings.
	# Optionally, set up initial database state or run SQL scripts if needed.
	# Expose the MariaDB Port:
	# Expose the port on which MariaDB listens (default is port 3306).
	# Define the Startup Command:
	# Specify the command to start the MariaDB service.