services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    environment:
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    networks:
      - inception

networks:
  inception:
